### ISSUE TITLE
colliding with elements which are owned by other players

### ISSUE THREAD

**Issue by ghostbuster91** [OrdonTeam/Hackathon3v2#25]
After player collide with e.g. zugar, the zugar should disappear and appear in new location (so basically zugar changed the location). But what if the zugar was owned by other player? How should we notice the owner about location change?

**Comment by OrdonTeam** [comment]
Collisions:
0. Each player move only his objects
1. When something collide with wall => move should be reverted
2. When two `AI` objects collide => move (or moves) should be reverted
3. When `userBot` collide with other `userBot` => move should be reverted
4. When `AI` collide with `userBot` =>
   4.a) within same owner => collision logic should have place
   4.b) `AI` collide with other  `userBot` => `AI` object should be given to `userBot` owner and he should apply collision logic.
   4.c) `userBot` collide with other `AI` => `AI` object should be taken from its owner and collision logic should be triggered instantly.

**Comment by ghostbuster91** [comment]
Agree, but do You have any idea how to implement point 4.b) ?

**Comment by OrdonTeam** [comment]
where do you see problem in this?

**Comment by ghostbuster91** [comment]
How to give the AI object to userBot owner? Each player is only returning objects which he is the owner. E.g. in point 4.c) we steal the object from other player and return list with this object, so other player can notice that his object is on this list and that hi is no longer it owner. But in this case we should send an object directly to particular player, shouldn't we?

**Comment by OrdonTeam** [comment]
Yes we should send it directly and this is not a problem.

czw., 16 kwi 2015, 21:31 Kasper użytkownik notifications@github.com
napisał:
