### ISSUE TITLE
Moving player or camera?

### ISSUE THREAD

**Issue by ghostbuster91** [OrdonTeam/Hackathon3v2#6]

**Comment by ghostbuster91** [comment]
Bardziej mi się podoba opcja z ruchoma kamerą i playerem pośrodku.  Przypuszczam ze przeliczanie wspolrzednych bedzie jakies zwariowane biorac pod uwage ze plansza ma sie zapetlac,.

**Comment by OrdonTeam** [comment]
Nieograniczona player na środku

**Comment by ghostbuster91** [comment]
agree
